# Generated by Django 3.0.7 on 2020-06-25 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(auto_created=1593120022.336734)),
                ('origin_latitude', models.FloatField()),
                ('origin_longitude', models.FloatField()),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('start_address', models.CharField(max_length=255)),
                ('end_address', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='neighborhood',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
